### ISSUE TITLE
SystemCheckError in Django 1.8.5

### ISSUE THREAD

**Issue by pacahon** [idlesign/django-sitemetrics#9]
Hello, I use template tag `{% sitemetrics by yandex for "XXX" %}` and don't want to use `django.contrib.site`, but in console I have an error:
```
ERRORS:
sitemetrics.Keycode.site: (fields.E300) Field defines a relation with model 'Site', which is either not installed, or is abstract.
```

Any suggestions?

**Comment by idlesign** [comment]
Hi,

There's no workaround unfortunatelly, since when `sitemetrics` is added into installed apps Django will create DB tables for it even you won't use them. The same goes for `Sites` contrib. So you still stuck with all those DB tables. 

On the bright side `Sites` doesn't create any feasible overhead, so I'd probably advise you not to bother.

**Comment by idlesign** [comment]
Considered closed. Feel free to reopen if required.
